# Generated by Django 5.2.8 on 2026-04-21 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sno", models.IntegerField()),
                ("sname", models.CharField(max_length=30)),
                ("sclass", models.IntegerField()),
                ("ssubject", models.CharField(max_length=30)),
                ("saddress", models.CharField(max_length=100)),
            ],
        ),
    ]
